### ISSUE TITLE
Driving events based on file change

### ISSUE THREAD

**Issue by willjschmitt** [PredixDev/px-file-upload#1]
As far as I can tell, there's no way to act upon a change in the file upload element. The `files` property doesn't set `notify`, so binding isn't possible, and there are no listeners defined on the upload element.

The only way I see to get the files is by an external user-driven event, or by polling the element. Can we add support for binding in any way, either through `notify` or `listeners`?

**Comment by Wandern** [comment]
I would like to second Will's request. Also if possible, I would like to see a more comprehensive demonstration of this component.

**Comment by randyaskin** [comment]
Added in PR #2 - kudos to @dylan-hantula! 👍 

I've also added information about the new event to the [demo page](http://predixdev.github.io/predix-ui/?show=px-file-upload&type=component) and added [a link to MDN](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications#Handling_the_upload_process_for_a_file) which explains how to actually upload files from a file upload field.
