### ISSUE TITLE
Multiple file upload only works when done all at once

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-file-upload#12]
## Expected behavior and actual behavior:

Expected: When I upload two files, one after the other, the second file is added to the list of files being uploaded (i.e. same result as if I had uploaded them at the same time).

Actual: When I upload two files, one after the other, the second file replaces the first, instead of being added to the file list.

## Steps to reproduce the problem:

Upload one (or multiple files) using either drag and drop or the Choose File button. Then do this again to add another file. The file/s added in the second batch will overwrite those in the first batch.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
v0.4.12

**Comment by randyaskin** [comment]
I believe this is the standard/intended behavior.

**Comment by kngauriet** [comment]
I am also facing same issue during upload file.

(1). We can not upload files from multiple folder locations at a time...We are forced to placed all files in a single folder and then to upload.
(2). If I click on browser button and cancel without selecting any files...previous selected files get clear.

Please let me know if there is a way to get it resolve other than modifying component by creating a local copy.

**Comment by randyaskin** [comment]
Again, both of those match the behavior of a [native HTML5 file input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) (which is what we're wrapping behind the scenes).
