### ISSUE TITLE
px-file-upload issue

### ISSUE THREAD

**Issue by kngauriet** [PredixDev/px-file-upload#15]
Hi,

Currently I am facing issues in uploading multiple file/image upload through predix px-file-upload component in IE browser (my current IE version 11). While it's working perfect in Chrome.

Please find attached screenshot for reference. Any help and suggestions are appreciated.

![predix_fileupload](https://user-images.githubusercontent.com/7467602/29048276-c3d1e1c2-7b9d-11e7-9121-b676adfb37ed.png)

**Comment by talimarcus** [comment]
@kngauriet fixed in https://github.com/PredixDev/px-file-upload/pull/16
