### ISSUE TITLE
"Drag and Drop" message should be configurable as to not confuse users

### ISSUE THREAD

**Issue by dylanhantula** [PredixDev/px-file-upload#4]
At the top of the component, in the #dndInstructions span element, there is a hard-coded message that reads, "Drag and drop files here, or click the button below." While this can be helpful in some scenarios, it can confuse users in situations when the component is meant to consume one and only one file - not multiple files. Given that the component allows for toggling whether multiple files can be selected (using the multiple property), the message should reflect the property by displaying "Drag and drop files here, or click the button below" when the user can select multiple files, and "Drag and drop a file here, or click the button below" when the user can select one and only one file.

Taking this one step further, some use cases could benefit from an entirely different custom message in that space. As such, the hard-coded "Drag and drop files here, or click the button below" message should be configurable via a property.

**Comment by runn-vermel** [comment]
Hi @dylanhantula 

Great suggestion! I went ahead and added that functionality in v0.3.0 - feel free to update to that version. :)

**Comment by NareshChennuri** [comment]
Is there any property to disable or enable the cloud icon and the message?
