### ISSUE TITLE
Drag and drop persists invalid file type

### ISSUE THREAD

**Issue by dylanhantula** [PredixDev/px-file-upload#5]
If you drag and drop a file type that is not supported (likely by accident), a message appears that reads "Invalid file type," which is great. If you then drag and drop a supported file type, however, the message still reads "Invalid file type" and the file-upload component does not accept this new file of the correct type. 

For example, I have a px-file-upload component with accept=".csv" as one of its attributes. If I drag and drop a .txt file, it tells me that this is an invalid file type. If I then drag and drop a .csv file, it still tells me that this is an invalid file type. 

The component should not persist the invalid file type message and should accept newly dragged and dropped files of the correct type

**Comment by randyaskin** [comment]
Good catch @dylanhantula - turns out it was supporting **one** switch from invalid-to-valid or vice versa, but not consistently re-validating every time a file was dropped. Fixed in v0.3.1.
